name: Main

# Run when a PR is closed against master
on: [push]

jobs:
  create_docker_image:
    runs-on: ubuntu-latest
    name: Create and run a Go application
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag gh_fetch .
    - name: 'Run Go application'
      run: 'docker run gh_fetch'
