name: Main

# Run when a PR is closed against master
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create_docker_image:
    runs-on: ubuntu-latest
    name: Create and run a Go application
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - id: 'Create Docker image'
        name: 'Create Docker image'
        uses: ./action.yaml
      - id: 'Run Go application'
        name: 'Run Go application'
        run: 'go run main.go'